nome = str(input('Digite o seu nome completo: ')).strip()
dividido = nome.split()
print('Seu nome completo é: {}'.format(nome))
print('Seu primeiro nome é: {}'.format(dividido[0]))
print('Seu último nome é: {}'.format(dividido[-1]))