times = ('Palmeiras','Grêmio','Atlético-MG','Flamengo','Botafogo','Bragantino','Fluminense','Athletico-PR','Internacional','Fortaleza','São Paulo','Cuiabá','Corinthians','Cruzeiro','Vasco da Gama','Bahia','Santos','Goiás','Coritiba','América-MG',)
print('='*100)
print(f'lista de times do Brasileirão: {times}')
print('='*100)
print(f'Os 5 primeiro colocados são: {times[0:5]}')
print('='*100)
print(f'Os 4 últimos são: {times[-4:]}')
print('='*100)
print(f'Times álfabeticas: {sorted(times)}')
print('='*100)
print(f'O Flamengo está na posição {times.index('Flamengo')+1}')